version: '3.8'
services:
  teamhack_dns:
    image: innovanon/teamhack_dns
    container_name:  teamhack_dns
    ports:
      - "0.0.0.0:53:53/udp"
    volumes:
      #- syslog-client:/etc/rsyslog.d:ro
      - teamhack:/var/teamhack/etc:ro
    restart:         always
    #network_mode:    service:vpn-s1
    healthcheck:
      test: ["CMD-SHELL", "true"]
      #test: ["CMD-SHELL", "nslookup cozyhosting.htb 0.0.0.0"]
      interval:      1m
      timeout:      30s
      retries:       10
    # TODO
    depends_on:
      postgres:
        condition: service_healthy
    #    condition: service_started
      syslog:
        condition: service_started
    #networks:
    #  network:
    #    ipv4_address: 10.5.0.6

#volumes:
#  teamhack: # /database.ini

