version: '3.8'
services:
  teamhack_dns:
    image: innovanon/teamhack_dns
    container_name:  teamhack_dns
    ports:
      - "0.0.0.0:53:53/udp"
    volumes:
      - teamhack-dns:/var/teamhack/etc:ro
      - syslog-client:/etc/rsyslog.d:ro
    restart:         always
    #network_mode:    service:vpn-s1
    healthcheck:
      test: ["CMD-SHELL", "nslookup hackthebox.com 0.0.0.0"]
      interval:      1m
      timeout:      30s
      retries:       10
    # TODO
    depends_on:
      postgres:
        condition: service_started
        #condition: service_healthy
      syslog:
        condition: service_started

volumes:
  teamhack-dns: # /database.ini

