[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.coverage.report]
fail_under = 80

[tool.coverage.run]
branch = true
include = ["src/mypackage/*"]
#source = ["."]
command_line = "-m unittest discover -s tests/"

