name: Hack the Box Team Support Services
permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
  #[workflow_call]
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    name: build package
    runs-on: ubuntu-latest
    steps:
    - name: install build deps
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: >
          libpq-dev python3 python-is-python3 python3-pip
        version: 1.0
    
    - name: Checkout code
      uses: actions/checkout@v3
      #with:
      #  path: "repo"

    - name: Build Deps
      run: |
        pip install build

    #- name: Optional Build Deps
    #  run: |
    #    pip install -e '.[dev]'

    - name: Build
      run: |
        python -m build

    # TODO new image
    - name: Install
      run: |
        pip install dist/*

    - name: Test Deps
      run: |
        pip install '.[test]'

    - name: Integration Test
      run: |
        export PATH=$HOME/.local/bin:$PATH
        pytest
        coverage run

    # TODO new image
    - name: Release Deps
      run: |
        pip install '.[rel]'

    - name: Release
      run: |
        export PATH=$HOME/.local/bin:$PATH
        python3 -m twine upload dist/*

    # TODO new image
    - name: Build Docker Image
      run: |
        docker build -t dnspy .
    #- name: Deploy Docker Image
    #  run: |
    #    docker deploy   dnspy

    #- name: sign installation package
    #  working-directory: ${{ github.workspace }}
    #  run: gpg --yes --detach-sig linux-${{ env.tag }}.tar.xz

    - name: Bump version and push tag
      id:   tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        fail_on_unmatched_files: true
        generate_release_notes: true
        files: |
          slapd_*.*.*+dfsg-*ubuntu*.*.*.*_amd64.deb
          libldap-*.*-*_*.*.*+dfsg-*ubuntu*.*.*.*_amd64.deb
          libldap-common_*.*.*+dfsg-*ubuntu*.*.*.*_all.deb

